name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.18.4'

      - name: Install and Build 🔧
        run: |
          npm ci
          npm yarn install
